title: "Bitcoin Mining News Bot"
description: "AI-generated Bitcoin mining news analysis and articles."
baseurl: ""
url: ""
theme: minima
permalink: pretty
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "articles"
      type: pages
    values:
      layout: article
  - scope:
      path: "reports"
      type: pages
    values:
      layout: report
