name: Tweet Bitcoin Mining News

on:
  schedule:
    # Run 16 times per day to respect 17 requests per 24 hours rate limit  
    # Every 90 minutes: 00:00, 01:30, 03:00, 04:30, 06:00, 07:30, etc.
    - cron: '0,30 */3 * * *'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          EVENTREGISTRY_API_KEY: ${{ secrets.EVENTREGISTRY_API_KEY }}

      - name: Upload runtime logs
        uses: actions/upload-artifact@v3
        if: always()  # Upload logs even if bot fails
        with:
          name: runtime-logs
          path: /home/runner/work/_temp/runtime-logs/
          retention-days: 7

      - name: Commit changes to posted articles
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add posted_articles.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update posted articles"
          git push
