name: Test API & Preview Threads

on:
  workflow_dispatch:
    inputs:
      max_articles:
        description: 'Maximum articles to preview (1-5)'
        required: false
        default: '3'
        type: choice
        options:
        - '1'
        - '2' 
        - '3'
        - '4'
        - '5'

jobs:
  test-and-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list | grep -E "(tweepy|eventregistry|google-genai)"
        
    - name: Test APIs and Generate Preview
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        EVENTREGISTRY_API_KEY: ${{ secrets.EVENTREGISTRY_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        MAX_ARTICLES: ${{ github.event.inputs.max_articles }}
      run: |
        python test_api_preview.py
    
    - name: Create GitHub Issue with Preview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create issue with the preview content
        issue_title="🧵 Thread Preview - $(date +'%Y-%m-%d %H:%M UTC')"
        
        gh issue create \
          --title "$issue_title" \
          --body-file preview_issue.md \
          --assignee "${{ github.actor }}"
          
        echo "✅ GitHub issue created with thread preview"
        
    - name: Cleanup
      run: |
        rm -f preview_issue.md